name: Build and Test

# Trigger on push to any branch and on pull requests
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    name: Build and Test Hello World
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc clang
        
    - name: Verify compiler installation
      run: |
        ${{ matrix.compiler }} --version
        
    - name: Run validation tests
      run: |
        chmod +x tests/validate.sh
        ./tests/validate.sh ${{ matrix.compiler }} hello_${{ matrix.compiler }}
        
    - name: Clean up build artifacts
      run: |
        rm -f hello_* *.exe *.out *.o